# Generated by Django 5.0.3 on 2024-03-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActualGroup',
            fields=[
                ('actual_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'actual_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('contacts_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('resource', models.TextField()),
            ],
            options={
                'db_table': 'contacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactsCourse',
            fields=[
                ('contacts_course_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'contacts_course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(blank=True, max_length=300, null=True)),
                ('term', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('course_group', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'course_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EdMId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ed_m_id',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EducationalMaterials',
            fields=[
                ('ed_m_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('url', models.TextField(blank=True, null=True)),
                ('material_type', models.TextField()),
            ],
            options={
                'db_table': 'educational_materials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupContacts',
            fields=[
                ('group_contacts_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'group_contacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Humans',
            fields=[
                ('isu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'humans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialsCourse',
            fields=[
                ('materials_course_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'materials_course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('date_of_pub', models.DateTimeField()),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsGroup',
            fields=[
                ('news_group_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'news_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.SmallIntegerField()),
                ('group_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=300)),
                ('curriculum', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('student_group_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'student_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subject',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('tasks_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('task_type', models.TextField()),
                ('date_of_pub', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
            ],
            options={
                'db_table': 'tasks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TasksCourse',
            fields=[
                ('tasks_course_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tasks_course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'teacher',
                'managed': False,
            },
        ),
    ]
